# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_val', models.CharField(max_length=30)),
                ('value', models.FloatField()),
            ],
        ),
    ]
